import { UserRepository } from "../repository/implements/user.repository";
import { OtpRepository } from "../repository/implements/otp.repository";
import { ChallengeProgressRepository } from "../repository/implements/proggress.repository";
import { TokenRepository } from "../repository/implements/token.repository";

import { UserService } from "../services/implements/user.service";
import { TokenService } from "../services/implements/token.service";
import { AuthController } from "../controllers/implements/auth.controller";
import { UserController } from "../controllers/implements/user.controller";

import { IUserService } from "../services/interfaces/user.services.interface";
import { ITokenService } from "../services/interfaces/token.service.interface";
import { IUserController } from "../controllers/interfaces/user.controller.interface";
import { IAuthController } from "../controllers/interfaces/auth.controller.interface";
import { ITokenProvider } from "../providers/interfaces/token.interface";
import { IEmailProvider } from "../providers/interfaces/email.interface";
import { IHashProvider } from "../providers/interfaces/crypto.interface";
import { JwtTokenProvider } from "../providers/implements/jwt.token";
import { HashProvider } from "../providers/implements/bcrypt.hasher";
import { EmailProvider } from "../providers/implements/email.sender";
import { IUserRepository } from "../repository/interfaces/user.repository.interface";
import { IOtpRepository } from "../repository/interfaces/otp.repository.interface";
import { IChallengeProgressRepository } from "../repository/interfaces/progress.repository.interface";
import { ITokenRepository } from "../repository/interfaces/token.repository.interface";
import { IOTPService } from "../services/interfaces/otp.services.interface";
import { INotificationRepository } from "../repository/interfaces/notification.repository.interface";
import { INotificationService } from "../services/interfaces/notification.service.interface";
import { INotificationController } from "../controllers/interfaces/notification.controller.interface";
import { NotificationRepository } from "../repository/implements/notification.repository";
import { NotificationService } from "../services/implements/notification.service";
import { NotificationController } from "../controllers/implements/notification.controller";
import { IAdminAnalyticsRepository } from "../repository/interfaces/analytics.repository.interface";
import { ILeaderboardRepository } from "../repository/interfaces/leaderboard.repostory.interface";
import { IAvatarRepository } from "../repository/interfaces/avatar.repository.interface";
import { IBannerRepository } from "../repository/interfaces/banner.repository.interface";
import { IBadgeRepository } from "../repository/interfaces/badge.repository.interface";
import { IChallengeRepository } from "../repository/interfaces/challange.repository.interface";
import { IConversationRepository } from "../repository/interfaces/conversation.repository.interface";
import { IGroupRepository } from "../repository/interfaces/group.repository.interface";
import { ILevelRepository } from "../repository/interfaces/level.repository.interface";
import { IMarketRepository } from "../repository/interfaces/market.repository.interface";
import { IMessageRepository } from "../repository/interfaces/message.repository.interface";
import { IPurchaseRepository } from "../repository/interfaces/purchase.repository.interface";
import { ISolutionRepository } from "../repository/interfaces/solution.repository.interface";
import { IGroupService } from "../services/interfaces/group.service.interface";
import { IMarketService } from "../services/interfaces/market.service.interface";
import { IChallengeProgressService } from "../services/interfaces/progress.service.interface";
import { IPurchaseService } from "../services/interfaces/purchase.service.interface";
import { IConversationService } from "../services/interfaces/conversation.service.interface";
import { IMessageService } from "../services/interfaces/message.service.interface";
import { ILevelService } from "../services/interfaces/level.service.interface";
import { ISolutionService } from "../services/interfaces/solution.service.interface";
import { IAdminAnalyticsService } from "../services/interfaces/analytics.service.interface";
import { IAvatarService } from "../services/interfaces/avatar.service.interface";
import { IBadgeService } from "../services/interfaces/badge.service.interface";
import { IBannerService } from "../services/interfaces/banner.service.interface";
import { IChallengeService } from "../services/interfaces/challange.service.interface";
import { IAdminAnalyticsController } from "../controllers/interfaces/analytics.controller.interface";
import { IAvatarController } from "../controllers/interfaces/avatar.controller.interface";
import { IBadgeController } from "../controllers/interfaces/badge.controller.interface";
import { IBannerController } from "../controllers/interfaces/banner.controller.interface";
import { IChallengeController } from "../controllers/interfaces/challange.controller.interface";
import { IConversationController } from "../controllers/interfaces/conversation.controller.interface";
import { IMessageController } from "../controllers/interfaces/message.controller.interface";
import { IGroupController } from "../controllers/interfaces/group.controller.interface";
import { ILevelController } from "../controllers/interfaces/level.controller.interface";
import { IChallengeProgressController } from "../controllers/interfaces/progress.controller.interface";
import { IPurchaseController } from "../controllers/interfaces/purchase.controller.interface";
import { ISolutionController } from "../controllers/interfaces/solution.controller.interface";
import { IMarketController } from "../controllers/interfaces/market.controller.interface";
import { AdminAnalyticsRepository } from "../repository/implements/analytics.repository";
import { AdminAnalyticsService } from "../services/implements/analytics.service";
import { LeaderboardRepository } from "../repository/implements/leaderboard.repostory";
import { AdminAnalyticsController } from "../controllers/implements/analytics.controller";
import { AvatarRepository } from "../repository/implements/avatar.repository";
import { ChallengeRepository } from "../repository/implements/challange.repository";
import { ChallengeService } from "../services/implements/challange.service";
import { ChallengeController } from "../controllers/implements/challange.controller";
import { ConversationRepository } from "../repository/implements/conversation.repository";
import { ConversationService } from "../services/implements/conversation.service";
import { GroupRepository } from "../repository/implements/group.repository";
import { GroupService } from "../services/implements/group.service";
import { GroupController } from "../controllers/implements/group.controller";
import { ConversationController } from "../controllers/implements/conversation.controller";
import { LevelRepository } from "../repository/implements/level.repository";
import { LevelService } from "../services/implements/level.service";
import { LevelController } from "../controllers/implements/level.controller";
import { MarketRepository } from "../repository/implements/market.repository";
import { MarketService } from "../services/implements/market.service";
import { MarketController } from "../controllers/implements/market.controller";
import { IMembershipRepository } from "../repository/interfaces/membership.repository.interface";
import { IMembershipService } from "../services/interfaces/membership.service.interface";
import { IMembershipController } from "../controllers/interfaces/membership.controller.interface";
import { MembershipRepository } from "../repository/implements/membership.repository";
import { MembershipService } from "../services/implements/membership.service";
import { MembershipController } from "../controllers/implements/membership.controller";
import { MessageRepository } from "../repository/implements/message.repository";
import { MessageService } from "../services/implements/message.service";
import { MessageController } from "../controllers/implements/message.controller";
import { connect } from "mongoose";
import { ChallengeProgressController } from "../controllers/implements/progress.controller";
import { PurchaseRepository } from "../repository/implements/purchase.repository";
import { PurchaseService } from "../services/implements/purchase.service";
import { PurchaseController } from "../controllers/implements/purchase.controller";
import { IReportRepository } from "../repository/interfaces/report.repository.interface";
import { IReportService } from "../services/interfaces/report.service.interface";
import { IReportController } from "../controllers/interfaces/report.controller.interface";
import { ReportRepository } from "../repository/implements/report.repository";
import { ReportService } from "../services/implements/report.service";
import { ReportController } from "../controllers/implements/report.controller";
import { SolutionRepository } from "../repository/implements/solution.repository";
import { SolutionService } from "../services/implements/solution.service";
import { SolutionController } from "../controllers/implements/solution.controller";

interface Container {
  tokenProv: ITokenProvider;
  hashProv: IHashProvider;
  emailProv: IEmailProvider;

  userRepo: IUserRepository;
  otpRepo: IOtpRepository;
  tokenRepo: ITokenRepository;
  notifyRepo: INotificationRepository;
  analysisRepo: IAdminAnalyticsRepository;
  leaderboardRepo: ILeaderboardRepository;
  avatarRepo: IAvatarRepository;
  bannerRepo: IBannerRepository;
  badgeRepo: IBadgeRepository;
  challengeRepo: IChallengeRepository;
  conversionRepo: IConversationRepository;
  messageRepo: IMessageRepository;
  groupRepo: IGroupRepository;
  levelRepo: ILevelRepository;
  marketRepo: IMarketRepository;
  membershipRepo: IMembershipRepository;
  progressRepo: IChallengeProgressRepository;
  purchaseRepo: IPurchaseRepository;
  reportRepo: IReportRepository;
  solutionRepo: ISolutionRepository;
  

  otpSvc: IOTPService;
  userSvc: IUserService;
  tokenSvc: ITokenService;
  notifySvc: INotificationService;
  analyticsSvc: IAdminAnalyticsService;
  avatarSvc: IAvatarService;
  bannerSvc: IBannerService;
  badgeSvc: IBadgeService;
  challengeSvc: IChallengeService;
  conversationSvc: IConversationService;
  messageSvc: IMessageService;
  groupSvc: IGroupService;
  levelSvc: ILevelService;
  marketSvc: IMarketService;
  membershipSvc: IMembershipService;
  progressSvc: IChallengeProgressService;
  purchaseSvc: IPurchaseService;
  reportSvc: IReportService;
  solutionSvc: ISolutionService;

  userCtrl: IUserController;
  authCtrl: IAuthController;
  notifyCtrl: INotificationController;
  analyticsCtrl: IAdminAnalyticsController;
  avatarCtrl: IAvatarController;
  badgeCtrl: IBadgeController;
  bannerCtrl: IBannerController;
  challengeCtrl: IChallengeController;
  conversationCtrl: IConversationController;
  messageCtrl: IMessageController;
  groupCtrl: IGroupController;
  levelCtrl: ILevelController;
  marketCtrl: IMarketController;
  membershipCtrl: IMembershipController;
  progressCtrl: IChallengeProgressController;
  purchaseCtrl: IPurchaseController;
  reportCtrl: IReportController;
  solutionCtrl: ISolutionController;
}

export const container = {} as Container;

container.tokenProv = new JwtTokenProvider();
container.hashProv = new HashProvider();
container.emailProv = new EmailProvider();

container.userRepo = new UserRepository();
container.otpRepo = new OtpRepository();
container.progressRepo = new ChallengeProgressRepository();
container.tokenRepo = new TokenRepository();
container.notifyRepo = new NotificationRepository();
container.analysisRepo = new AdminAnalyticsRepository();
container.leaderboardRepo = new LeaderboardRepository();
container.avatarRepo = new AvatarRepository();
container.challengeRepo = new ChallengeRepository();
container.conversionRepo = new ConversationRepository();
container.groupRepo = new GroupRepository();
container.levelRepo = new LevelRepository();
container.marketRepo = new MarketRepository();
container.membershipRepo = new MembershipRepository();
container.messageRepo = new MessageRepository();
container.purchaseRepo = new PurchaseRepository();
container.reportRepo = new ReportRepository();
container.solutionRepo = new SolutionRepository();

container.tokenSvc = new TokenService(container.tokenRepo);
container.userSvc = new UserService(
  container.userRepo,
  container.otpSvc,
  container.progressRepo,
  container.tokenProv,
  container.emailProv,
  container.hashProv
);
container.notifySvc = new NotificationService(container.notifyRepo);
container.analyticsSvc = new AdminAnalyticsService(container.analysisRepo,container.leaderboardRepo);
container.challengeSvc = new ChallengeService(container.challengeRepo,container.levelRepo,container.userRepo,container.progressRepo);
container.groupSvc = new GroupService(container.groupRepo,container.conversionRepo);
container.conversationSvc = new ConversationService(container.conversionRepo,container.groupRepo,container.userRepo);
container.levelSvc = new LevelService(container.levelRepo,container.userRepo);
container.marketSvc = new MarketService(container.marketRepo,container.userRepo);
container.membershipSvc = new MembershipService(container.membershipRepo);
container.messageSvc = new MessageService(container.messageRepo);
container.purchaseSvc = new PurchaseService(container.purchaseRepo,container.membershipRepo, container.userRepo);
container.reportSvc = new ReportService(container.reportRepo);
container.solutionSvc = new SolutionService(container.solutionRepo);

container.userCtrl = new UserController(container.userSvc, container.tokenSvc);
container.authCtrl = new AuthController(container.userSvc, container.tokenSvc);
container.progressCtrl = new ChallengeProgressController(container.progressSvc);
container.notifyCtrl = new NotificationController(container.notifySvc,container.userSvc);
container.analyticsCtrl = new AdminAnalyticsController(container.analyticsSvc);
container.challengeCtrl = new ChallengeController(container.challengeSvc);
container.groupCtrl = new GroupController(container.groupSvc);
container.conversationCtrl = new ConversationController(container.conversationSvc);
container.levelCtrl = new LevelController(container.levelSvc);
container.marketCtrl = new MarketController(container.marketSvc);
container.membershipCtrl = new MembershipController(container.membershipSvc);
container.messageCtrl = new MessageController(container.messageSvc);
container.purchaseCtrl = new PurchaseController(container.purchaseSvc);
container.reportCtrl = new ReportController(container.reportSvc);
container.solutionCtrl = new SolutionController(container.solutionSvc);
