export const mockChallenges = [
  {
    _id: "1",
    title: "Sum of Two Numbers",
    description: "Write a function that returns the sum of two numbers.",
    instructions: "Take two integers as input and return their sum.",
    type: "code",
    level: "novice",
    timeLimit: 10,
    tags: ["Math", "Basics"],
    hints: ["Use + operator", "Return the sum directly"],
    requiredSkills: ["JavaScript Basics"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "completed",
    completedUsers: 120,
    successRate: 95,
    functionSignature: "function sum(a, b) {}",
    initialCode: "function sum(a, b) {\n  \n}",
    solutionCode: "function sum(a, b) { return a + b; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 15),
    xpRewards: 50,
  },
  {
    _id: "2",
    title: "Reverse a String",
    description: "Reverse the given string.",
    instructions: "Take a string input and return it reversed.",
    type: "code",
    level: "novice",
    timeLimit: 10,
    tags: ["String", "Basics"],
    hints: ["Use split and reverse", "Or loop from end to start"],
    requiredSkills: ["JavaScript Basics", "Strings"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "failed-output",
    completedUsers: 95,
    successRate: 70,
    functionSignature: "function reverseStr(str) {}",
    initialCode: "function reverseStr(str) {\n  \n}",
    solutionCode:
      "function reverseStr(str) { return str.split('').reverse().join(''); }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 10),
    xpRewards: 40,
  },
  {
    _id: "3",
    title: "Caesar Cipher",
    description: "Encrypt text using Caesar cipher with a shift of 3.",
    instructions: "Take a string and return the encrypted text.",
    type: "cipher",
    level: "adept",
    timeLimit: 15,
    tags: ["Cipher", "Security"],
    hints: ["Use charCodeAt and fromCharCode", "Handle wrap around A-Z"],
    requiredSkills: ["Strings", "Encryption Basics"],
    isPremium: false,
    isKeyRequired: true,
    userStatus: "pending",
    completedUsers: 60,
    successRate: 65,
    functionSignature: "function caesarCipher(str) {}",
    initialCode: "function caesarCipher(str) {\n  \n}",
    solutionCode:
      "function caesarCipher(str) { return str.replace(/[a-z]/gi, c => String.fromCharCode((c.charCodeAt(0) - 65 + 3) % 26 + 65)); }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 20),
    xpRewards: 70,
  },
  {
    _id: "4",
    title: "Factorial",
    description: "Find the factorial of a number.",
    instructions: "Return the factorial using recursion.",
    type: "code",
    level: "novice",
    timeLimit: 15,
    tags: ["Math", "Recursion"],
    hints: ["Base case n===0", "Recursive call"],
    requiredSkills: ["Recursion", "Math"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "completed",
    completedUsers: 88,
    successRate: 82,
    functionSignature: "function factorial(n) {}",
    initialCode: "function factorial(n) {\n  \n}",
    solutionCode:
      "function factorial(n) { return n === 0 ? 1 : n * factorial(n-1); }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 25),
    xpRewards: 60,
  },
  {
    _id: "5",
    title: "Palindrome Check",
    description: "Check if a string is a palindrome.",
    instructions: "Return true if string reads the same backward.",
    type: "code",
    level: "novice",
    timeLimit: 15,
    tags: ["String", "Logic"],
    hints: ["Reverse and compare", "Ignore case"],
    requiredSkills: ["Strings"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "failed-timeout",
    completedUsers: 75,
    successRate: 66,
    functionSignature: "function isPalindrome(str) {}",
    initialCode: "function isPalindrome(str) {\n  \n}",
    solutionCode:
      "function isPalindrome(str) { let s = str.toLowerCase(); return s === s.split('').reverse().join(''); }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 15),
    xpRewards: 55,
  },
  {
    _id: "6",
    title: "Fibonacci Sequence",
    description: "Generate Fibonacci sequence up to n terms.",
    instructions: "Return an array of n Fibonacci numbers.",
    type: "code",
    level: "adept",
    timeLimit: 20,
    tags: ["Math", "Recursion", "DP"],
    hints: ["Start with 0,1", "Use loop or recursion"],
    requiredSkills: ["Recursion", "Loops"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "completed",
    completedUsers: 64,
    successRate: 74,
    functionSignature: "function fibonacci(n) {}",
    initialCode: "function fibonacci(n) {\n  \n}",
    solutionCode:
      "function fibonacci(n) { let arr=[0,1]; for(let i=2;i<n;i++){arr[i]=arr[i-1]+arr[i-2]} return arr.slice(0,n); }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 30),
    xpRewards: 80,
  },
  {
    _id: "7",
    title: "Find Largest Number",
    description: "Find the largest number in an array.",
    instructions: "Return max value from array.",
    type: "code",
    level: "novice",
    timeLimit: 10,
    tags: ["Array", "Math"],
    hints: ["Use Math.max", "Or loop compare"],
    requiredSkills: ["Arrays"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "completed",
    completedUsers: 102,
    successRate: 90,
    functionSignature: "function maxInArray(arr) {}",
    initialCode: "function maxInArray(arr) {\n  \n}",
    solutionCode: "function maxInArray(arr) { return Math.max(...arr); }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 20),
    xpRewards: 45,
  },
  {
    _id: "8",
    title: "Binary Search",
    description: "Perform binary search in a sorted array.",
    instructions: "Return index if found else -1.",
    type: "code",
    level: "adept",
    timeLimit: 25,
    tags: ["Search", "Algorithm"],
    hints: ["Divide array", "Check mid element"],
    requiredSkills: ["Arrays", "Binary Search"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "pending",
    completedUsers: 56,
    successRate: 69,
    functionSignature: "function binarySearch(arr, target) {}",
    initialCode: "function binarySearch(arr, target) {\n  \n}",
    solutionCode:
      "function binarySearch(arr, target) { let l=0,r=arr.length-1; while(l<=r){let m=Math.floor((l+r)/2); if(arr[m]===target)return m; if(arr[m]<target)l=m+1; else r=m-1;} return -1; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 35),
    xpRewards: 85,
  },
  {
    _id: "9",
    title: "Vowel Count",
    description: "Count vowels in a given string.",
    instructions: "Return number of vowels.",
    type: "code",
    level: "novice",
    timeLimit: 10,
    tags: ["String"],
    hints: ["Regex match", "Loop check"],
    requiredSkills: ["Strings"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "completed",
    completedUsers: 110,
    successRate: 92,
    functionSignature: "function countVowels(str) {}",
    initialCode: "function countVowels(str) {\n  \n}",
    solutionCode:
      "function countVowels(str) { return (str.match(/[aeiou]/gi) || []).length; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 15),
    xpRewards: 35,
  },
  {
    _id: "10",
    title: "Prime Number Check",
    description: "Check if a number is prime.",
    instructions: "Return true for prime numbers.",
    type: "code",
    level: "adept",
    timeLimit: 15,
    tags: ["Math"],
    hints: ["Check divisibility up to sqrt(n)"],
    requiredSkills: ["Math"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "failed-output",
    completedUsers: 78,
    successRate: 68,
    functionSignature: "function isPrime(n) {}",
    initialCode: "function isPrime(n) {\n  \n}",
    solutionCode:
      "function isPrime(n) { if(n<2)return false; for(let i=2;i<=Math.sqrt(n);i++){ if(n%i===0)return false;} return true; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 20),
    xpRewards: 60,
  },
  {
    _id: "11",
    title: "Prime Number Check",
    description: "Check if a number is prime.",
    instructions: "Return true for prime numbers.",
    type: "code",
    level: "adept",
    timeLimit: 15,
    tags: ["Math"],
    hints: ["Check divisibility up to sqrt(n)"],
    requiredSkills: ["Math"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "failed-output",
    completedUsers: 78,
    successRate: 68,
    functionSignature: "function isPrime(n) {}",
    initialCode: "function isPrime(n) {\n  \n}",
    solutionCode:
      "function isPrime(n) { if(n<2)return false; for(let i=2;i<=Math.sqrt(n);i++){ if(n%i===0)return false;} return true; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 20),
    xpRewards: 60,
  },
  {
    _id: "12",
    title: "Prime Number Check",
    description: "Check if a number is prime.",
    instructions: "Return true for prime numbers.",
    type: "code",
    level: "adept",
    timeLimit: 15,
    tags: ["Math"],
    hints: ["Check divisibility up to sqrt(n)"],
    requiredSkills: ["Math"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "failed-output",
    completedUsers: 78,
    successRate: 68,
    functionSignature: "function isPrime(n) {}",
    initialCode: "function isPrime(n) {\n  \n}",
    solutionCode:
      "function isPrime(n) { if(n<2)return false; for(let i=2;i<=Math.sqrt(n);i++){ if(n%i===0)return false;} return true; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 20),
    xpRewards: 60,
  },
  {
    _id: "13",
    title: "Prime Number Check",
    description: "Check if a number is prime.",
    instructions: "Return true for prime numbers.",
    type: "code",
    level: "adept",
    timeLimit: 15,
    tags: ["Math"],
    hints: ["Check divisibility up to sqrt(n)"],
    requiredSkills: ["Math"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "failed-output",
    completedUsers: 78,
    successRate: 68,
    functionSignature: "function isPrime(n) {}",
    initialCode: "function isPrime(n) {\n  \n}",
    solutionCode:
      "function isPrime(n) { if(n<2)return false; for(let i=2;i<=Math.sqrt(n);i++){ if(n%i===0)return false;} return true; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 20),
    xpRewards: 60,
  },
  {
    _id: "14",
    title: "Prime Number Check",
    description: "Check if a number is prime.",
    instructions: "Return true for prime numbers.",
    type: "code",
    level: "adept",
    timeLimit: 15,
    tags: ["Math"],
    hints: ["Check divisibility up to sqrt(n)"],
    requiredSkills: ["Math"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "failed-output",
    completedUsers: 78,
    successRate: 68,
    functionSignature: "function isPrime(n) {}",
    initialCode: "function isPrime(n) {\n  \n}",
    solutionCode:
      "function isPrime(n) { if(n<2)return false; for(let i=2;i<=Math.sqrt(n);i++){ if(n%i===0)return false;} return true; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 20),
    xpRewards: 60,
  },
  {
    _id: "15",
    title: "Prime Number Check",
    description: "Check if a number is prime.",
    instructions: "Return true for prime numbers.",
    type: "code",
    level: "adept",
    timeLimit: 15,
    tags: ["Math"],
    hints: ["Check divisibility up to sqrt(n)"],
    requiredSkills: ["Math"],
    isPremium: false,
    isKeyRequired: false,
    userStatus: "failed-output",
    completedUsers: 78,
    successRate: 68,
    functionSignature: "function isPrime(n) {}",
    initialCode: "function isPrime(n) {\n  \n}",
    solutionCode:
      "function isPrime(n) { if(n<2)return false; for(let i=2;i<=Math.sqrt(n);i++){ if(n%i===0)return false;} return true; }",
    status: "active",
    isActive: true,
    startTime: new Date(),
    endTime: new Date(Date.now() + 1000 * 60 * 20),
    xpRewards: 60,
  },
];

export const dummyChallengeData = {
  id: "two-sum",
  title: "Two Sum",
  difficulty: "Easy",
  description:
    "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice. You can return the answer in any order.",

  constraints: [
    "2 ≤ nums.length ≤ 10⁴",
    "-10⁹ ≤ nums[i] ≤ 10⁹",
    "-10⁹ ≤ target ≤ 10⁹",
    "Only one valid answer exists.",
    "Follow-up: Can you come up with an algorithm that is less than O(n²) time complexity?",
  ],

  sampleTestCases: [
    {
      input: "nums = [2,7,11,15], target = 9",
      output: "[0,1]",
      explanation: "Because nums[0] + nums[1] == 9, we return [0, 1].",
    },
    {
      input: "nums = [3,2,4], target = 6",
      output: "[1,2]",
      explanation: "Because nums[1] + nums[2] == 6, we return [1, 2].",
    },
    {
      input: "nums = [3,3], target = 6",
      output: "[0,1]",
      explanation: "Because nums[0] + nums[1] == 6, we return [0, 1].",
    },
  ],

  referenceImages: [
    {
      url: "https://via.placeholder.com/400x200/0085e5/ffffff?text=Two+Sum+Visualization",
      caption:
        "Visual representation of finding two numbers that sum to target",
    },
    {
      url: "https://via.placeholder.com/400x150/22c55e/ffffff?text=Hash+Map+Approach",
      caption: "Hash map optimization approach diagram",
    },
  ],

  referenceLinks: [
    {
      url: "https://en.wikipedia.org/wiki/Hash_table",
      title: "Hash Table - Wikipedia",
      description: "Learn about hash tables and their O(1) average lookup time",
    },
    {
      url: "https://www.geeksforgeeks.org/two-sum-problem/",
      title: "Two Sum Problem - GeeksforGeeks",
      description:
        "Detailed explanation with multiple approaches and implementations",
    },
    {
      url: "https://leetcode.com/problems/two-sum/discuss/",
      title: "LeetCode Discussion Forum",
      description: "Community solutions and optimization techniques",
    },
    {
      url: "https://www.youtube.com/watch?v=KLlXCFG5TnA",
      title: "Two Sum - Video Tutorial",
      description: "Step-by-step video explanation of the hash map approach",
    },
  ],

  patterns: [
    "Hash Table",
    "Array",
    "Two Pointers",
    "Complement Search",
    "Index Mapping",
    "Time-Space Tradeoff",
  ],

  timeComplexity: "O(n)",
  spaceComplexity: "O(n)",

  tags: ["Easy", "Array", "Hash Table"],
  companies: ["Amazon", "Google", "Microsoft", "Facebook"],
  acceptanceRate: "49.1%",
  totalSubmissions: "8.2M",
  category: "Arrays & Hashing",

  hints: [
    "A really brute force way would be to search for all possible pairs of numbers but that would be too slow. Again, it's best to try out brute force solutions for just for completeness. It is from these brute force solutions that you can come up with optimizations.",
    "So, if we fix one of the numbers, say x, we have to scan the entire array to find the next number y which is value - x where value is the input parameter. Can we change our array somehow so that this search becomes faster?",
    "The second train of thought is, without changing the array, can we use additional space somehow? Like maybe a hash map to speed up the search?",
  ],

  solutions: [
    {
      language: "javascript",
      code: `var twoSum = function(nums, target) {
    const map = new Map();
    
    for (let i = 0; i < nums.length; i++) {
        const complement = target - nums[i];
        
        if (map.has(complement)) {
            return [map.get(complement), i];
        }
        
        map.set(nums[i], i);
    }
    
    return [];
};`,
      complexity: {
        time: "O(n)",
        space: "O(n)",
      },
      approach: "Hash Map",
    },
    {
      language: "python",
      code: `def twoSum(nums, target):
    hashmap = {}
    
    for i in range(len(nums)):
        complement = target - nums[i]
        
        if complement in hashmap:
            return [hashmap[complement], i]
        
        hashmap[nums[i]] = i
    
    return []`,
      complexity: {
        time: "O(n)",
        space: "O(n)",
      },
      approach: "Hash Map",
    },
  ],

  submissionHistory: [
    {
      id: "sub_001",
      timestamp: "2024-03-15T10:30:00Z",
      status: "Accepted",
      runtime: "52ms",
      memory: "44.2MB",
      language: "javascript",
      code: "// Previous successful submission code...",
      testsPassed: "57/57",
    },
    {
      id: "sub_002",
      timestamp: "2024-03-15T10:25:00Z",
      status: "Wrong Answer",
      runtime: "N/A",
      memory: "N/A",
      language: "javascript",
      code: "// Previous failed submission code...",
      testsPassed: "23/57",
      error: "Expected [0,1] but got [1,0]",
    },
  ],
};

export const mockLanguages = [
    { name: "C++", extension: "cpp" },
    { name: "Java", extension: "java" },
    { name: "Python", extension: "py" },
    { name: "Python3", extension: "py3" },
    { name: "C", extension: "c" },
    { name: "C#", extension: "cs" },
    { name: "JavaScript", extension: "js" },
    { name: "TypeScript", extension: "ts" },
    { name: "PHP", extension: "php" },
    { name: "Swift", extension: "swift" },
    { name: "Kotlin", extension: "kt" },
    { name: "Dart", extension: "dart" },
    { name: "Go", extension: "go" },
    { name: "Ruby", extension: "rb" },
    { name: "Scala", extension: "scala" },
    { name: "Rust", extension: "rs" },
    { name: "Racket", extension: "rkt" },
    { name: "Erlang", extension: "erl" },
    { name: "Elixir", extension: "ex" }
  ];